name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * *'  # Agendamento para todo dia às 09:00 (UTC)

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with Allure
        run: npm run e2e

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Artifacts
          path: |
            cypress/videos/
            cypress/screenshots/

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results
          path: allure-results/

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure-Report
          path: allure-report/

      - name: Send Slack notification on failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -z "${GITHUB_RUN_URL}" ]; then
            GITHUB_RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          fi
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"⚠️ O job *Cypress Tests* falhou no commit: <${GITHUB_SHA}|${GITHUB_SHA}> no projeto: ${GITHUB_REPOSITORY}. Verifique os relatórios de teste em: <${GITHUB_RUN_URL}|Clique aqui para ver os detalhes>\", \"icon_url\": \"https://example.com/automation-icon.png\"}" \
          $SLACK_WEBHOOK_URL